"""Agregar campos binarios a fotos

Revision ID: 305968ec3d79
Revises: 7d82a6643747
Create Date: 2025-11-27 10:07:28.275951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305968ec3d79'
down_revision = '7d82a6643747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotos_mascotas_desaparecidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nombre_archivo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tamano_bytes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotos_mascotas_desaparecidas', schema=None) as batch_op:
        batch_op.drop_column('tamano_bytes')
        batch_op.drop_column('nombre_archivo')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('data')

    # ### end Alembic commands ###
