"""initial schema

Revision ID: 7d82a6643747
Revises: 
Create Date: 2025-11-16 10:09:15.411028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d82a6643747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('propietario_email', sa.String(length=120), nullable=False),
    sa.Column('propietario_telefono', sa.String(length=20), nullable=False),
    sa.Column('zona', sa.String(length=50), nullable=False),
    sa.Column('tipo_registro', sa.String(length=12), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('chip', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=8), nullable=False),
    sa.Column('fecha_aparecida', sa.Date(), nullable=True),
    sa.Column('estado_aparecida', sa.String(length=6), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('tamano', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.CheckConstraint("sexo IN ('macho','hembra','no_sabe')", name='chk_sexo_valido'),
    sa.CheckConstraint("tamano IN ('pequeño','mediano','grande')", name='chk_tamano_valido'),
    sa.CheckConstraint("tipo_registro IN ('desaparecida','encontrada')", name='chk_tipo_registro_valido'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('propietario_email', 'tipo_registro', 'nombre', 'zona', 'especie', 'color', 'tamano', 'fecha_registro', name='uix_email_tipo_nombre_zona_especie_color_tamano_fecha')
    )
    op.create_table('fotos_mascotas_desaparecidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tipo_foto', sa.String(length=30), nullable=False),
    sa.Column('ruta', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascota.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mascota_id', 'tipo_foto', name='uix_foto_mascota_tipo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos_mascotas_desaparecidas')
    op.drop_table('mascota')
    # ### end Alembic commands ###
